# Generated by Django 3.2.20 on 2023-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0011_auto_20230803_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='offer_zone',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer_zone',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer_zone',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
