# Generated by Django 3.2.20 on 2023-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0014_user_registration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='joindate',
            field=models.DateField(null=True),
        ),
    ]
